package fr.cellule.core

/*
 * Le catalogue des objectifs de cinéma.
 *
 * Mêmes principes que pour les caméras : attributions recoupées, ordres de
 * grandeur plutôt que fausse précision. Les ouvertures sont données en T, la
 * lumière réellement transmise, et non en f, l'ouverture géométrique — c'est
 * l'unité du cinéma, parce qu'un raccord de diaph entre deux optiques doit
 * donner la même exposition.
 */

val ETAGERES_OBJECTIFS: List<Etagere<Objectif>> = listOf(
    Etagere("Zeiss et ARRI", zeissEtArri()),
    Etagere("Cooke", cooke()),
    Etagere("Angénieux", angenieux()),
    Etagere("Leitz", leitz()),
    Etagere("Panavision", panavisionOptiques()),
    Etagere("Anamorphiques de caractère", anamorphiques()),
    Etagere("Vintage et alternatives", vintageEtAlternatives())
)

private fun zeissEtArri(): List<Objectif> = listOf(
    Objectif(
        nom = "Super Speed",
        fabricant = "Zeiss",
        annee = 1975,
        categorie = "Focales fixes sphériques, vintage",
        silhouette = Silhouette.ANCIENNE,
        focales = "18 à 85 mm (série de base)",
        ouverture = "T1.3 (T1.4 sur la Mark I)",
        couverture = "Super 35",
        monture = "PL",
        disponibilite = Disponibilite.PLUS_FABRIQUEE,
        punchline = "Les fixes ultra-lumineuses des années 1970, devenues des vintage très demandées.",
        histoire = "Apparues au milieu des années 1970 pour tourner en lumière faible, elles ont été produites en plusieurs générations (Mark I, II, III) pendant près de trente ans. Longtemps simples outils de travail, elles sont devenues recherchées pour leur caractère, face à des optiques modernes jugées trop cliniques.",
        ficheTechnique = "Série de base de 18, 25, 35, 50 et 85 mm, ouverture T1.3 à partir de la Mark II, couverture Super 35. Corps compacts et légers. Traitements anti-reflets de leur époque : flares et douceur à pleine ouverture que les séries modernes ont éliminés.",
        commentLUtiliser = "À pleine ouverture, la profondeur de champ est infime : l'assistant opérateur doit être très précis. On les choisit pour adoucir un capteur numérique trop net, ou pour tourner la nuit en lumière existante.",
        atouts = "Luminosité, compacité, rendu doux et chaleureux, flares de caractère.",
        limites = "Couverture limitée au Super 35, mécanique ancienne à faire vérifier, mise au point délicate à pleine ouverture.",
        films = listOf("Shining" par "John Alcott"),
        aRetenir = "Leur ouverture de T1.3 était révolutionnaire : elle permettait de tourner en lumière existante là où il fallait auparavant des projecteurs."
    ),
    Objectif(
        nom = "Ultra Prime",
        fabricant = "ARRI / Zeiss",
        annee = 1999,
        categorie = "Focales fixes sphériques",
        silhouette = Silhouette.FIXE,
        focales = "8 à 180 mm",
        ouverture = "T1.9 (T2.8 pour le 8 mm)",
        couverture = "Super 35",
        monture = "PL",
        disponibilite = Disponibilite.PLUS_FABRIQUEE,
        punchline = "La série de travail des années 2000 : légère, homogène, nette.",
        histoire = "Lancées en 1999 par ARRI et Zeiss, elles offrent une très large gamme de focales légères et homogènes, du 8 mm au 180 mm. Elles ont servi sur d'innombrables productions de la fin de la pellicule et des débuts du numérique.",
        ficheTechnique = "Jusqu'à seize focales de 8 à 180 mm, T1.9 pour la plupart, couverture Super 35. Distorsion très faible, y compris sur le 8 mm rectilinéaire, un ultra grand-angle rare. Même diamètre avant sur toute la série pour changer d'optique sans refaire les réglages de la matte box.",
        commentLUtiliser = "Une série polyvalente qu'on emporte pour tout un film. Leur homogénéité de couleur et de contraste permet de changer de focale sans rupture à l'étalonnage.",
        atouts = "Légèreté, homogénéité, gamme très étendue, piqué propre sans dureté.",
        limites = "Couverture limitée au Super 35, rendu jugé neutre voire impersonnel aujourd'hui, moins lumineuses que les séries à T1.3.",
        films = listOf("Le Seigneur des anneaux" par "Andrew Lesnie"),
        aRetenir = "Leur 8 mm « R », pour rectilinéaire, garde les lignes droites droites : un ultra grand-angle sans l'effet fish-eye."
    ),
    Objectif(
        nom = "Master Prime",
        fabricant = "ARRI / Zeiss",
        annee = 2005,
        categorie = "Focales fixes sphériques, très lumineuses",
        silhouette = Silhouette.FIXE,
        focales = "12 à 150 mm",
        ouverture = "T1.3",
        couverture = "Super 35",
        monture = "PL",
        disponibilite = Disponibilite.ACHAT,
        punchline = "Les plus lumineuses et les plus piquées de leur génération : la netteté clinique.",
        histoire = "Sorties en 2005, elles poussent la luminosité à T1.3 sur toute la série tout en gardant une image extrêmement nette et corrigée. Elles ont incarné l'image « parfaite » du cinéma numérique naissant.",
        ficheTechnique = "Série de 12 à 150 mm, T1.3 pour toutes les focales. Distorsion, aberrations et respiration de mise au point quasi nulles. Couverture Super 35. Optiques lourdes et volumineuses pour leur format.",
        commentLUtiliser = "Pour tourner en très basse lumière sans perdre en netteté, ou quand la précision du détail compte : effets visuels, science-fiction. Leur faible respiration permet de changer de point sans que le cadre ne « pompe ».",
        atouts = "Piqué et contraste élevés même à pleine ouverture, homogénéité parfaite, idéales pour les effets visuels.",
        limites = "Rendu jugé froid ou clinique, poids, couverture Super 35 à l'heure du grand format.",
        films = listOf(
            "Blade Runner 2049" par "Roger Deakins",
            "Top Gun: Maverick (focales longues)" par "Claudio Miranda"
        ),
        aRetenir = "Roger Deakins les a choisies pour Blade Runner 2049 parce que c'étaient, selon lui, les optiques les plus rapides et les plus nettes qu'il pouvait trouver."
    ),
    Objectif(
        nom = "CP.3",
        fabricant = "Zeiss",
        annee = 2016,
        categorie = "Focales fixes compactes, monture interchangeable",
        silhouette = Silhouette.FIXE,
        focales = "15 à 135 mm",
        ouverture = "T2.1 (T2.9 aux plus courtes)",
        couverture = "Plein format",
        monture = "Interchangeable : PL, EF, E, MFT, F",
        disponibilite = Disponibilite.ACHAT,
        punchline = "Des fixes de cinéma abordables, dont la monture s'adapte à la caméra du jour.",
        histoire = "Troisième génération des Compact Primes de Zeiss, sortie en 2016, elles apportent la mécanique d'une optique de cinéma — bagues crantées, longue course de mise au point — à un prix accessible aux petites productions.",
        ficheTechnique = "Série de 15 à 135 mm, T2.1 pour la plupart des focales, couverture plein format. Montures interchangeables PL, EF, E, MFT et F. Diamètre avant commun et bagues aux mêmes positions sur toute la série. Version XD avec données d'objectif pour la post-production.",
        commentLUtiliser = "La série de départ idéale pour une petite société ou un chef opérateur qui change souvent de caméra : on remonte la bonne monture et l'on garde les mêmes optiques.",
        atouts = "Prix, compacité, polyvalence de monture, image nette et homogène.",
        limites = "Moins lumineuses que les séries haut de gamme, rendu sage, sans caractère marqué.",
        films = listOf("All That Breathes (documentaire)" par "Riju Das"),
        aRetenir = "All That Breathes, documentaire sur deux frères qui soignent des rapaces à Delhi, a été tourné en partie avec elles et nommé à l'Oscar du meilleur documentaire."
    ),
    Objectif(
        nom = "Supreme Prime",
        fabricant = "Zeiss",
        annee = 2018,
        categorie = "Focales fixes plein format",
        silhouette = Silhouette.FIXE,
        focales = "15 à 200 mm",
        ouverture = "T1.5 pour la plupart",
        couverture = "Plein format",
        monture = "PL",
        disponibilite = Disponibilite.ACHAT,
        punchline = "Le grand format selon Zeiss : net, mais adouci pour les visages.",
        histoire = "Lancées en 2018 pour accompagner le passage du cinéma au grand format, elles corrigent la réputation de froideur des séries précédentes de la marque : netteté au centre, transitions douces vers le flou, carnations chaleureuses. Une variante « Radiance » ajoute des flares dessinés.",
        ficheTechnique = "Série de 15 à 200 mm, T1.5 pour la plupart des focales, couverture plein format. Corps homogènes et assez compacts. Données d'objectif intégrées. Déclinaison Radiance aux traitements qui provoquent des reflets bleus contrôlés.",
        commentLUtiliser = "Série principale d'un tournage grand format, gardée du premier au dernier jour pour l'homogénéité. Les Radiance se sortent pour les scènes où l'on veut des flares sans perdre le contraste.",
        atouts = "Luminosité en grand format, mise au point douce, homogénéité de toute la série.",
        limites = "Coût élevé ; ceux qui cherchent un vrai caractère vintage préfèrent des séries plus anciennes.",
        films = listOf(
            "Glass Onion" par "Steve Yedlin",
            "Barbarian" par "Zach Kuperstein"
        ),
        aRetenir = "Leur arrivée coïncide avec le moment où ARRI, Sony et RED passaient tous au plein format ou au-delà : il fallait des optiques pensées pour ces grands capteurs."
    ),
    Objectif(
        nom = "Signature Prime",
        fabricant = "ARRI",
        annee = 2018,
        categorie = "Focales fixes grand format",
        silhouette = Silhouette.FIXE,
        focales = "12 à 280 mm",
        ouverture = "T1.8",
        couverture = "Grand format (LF)",
        monture = "LPL",
        disponibilite = Disponibilite.ACHAT,
        punchline = "Les optiques maison d'ARRI pour le grand format : douces, homogènes, légères.",
        histoire = "Présentées en 2018 avec l'ALEXA LF et la monture LPL, elles marquent le moment où ARRI dessine ses propres optiques grand format. Leur rendu vise l'inverse de la netteté clinique : carnations douces, noirs profonds, flou rond.",
        ficheTechnique = "Série de 12 à 280 mm, T1.8 sur toute la gamme, couverture grand format. Corps en magnésium, légers pour leur taille. Porte-filtre magnétique à l'arrière pour placer un filet de diffusion. Données d'objectif transmises par la monture LPL.",
        commentLUtiliser = "On règle la texture de l'image avec un filet à l'arrière plutôt qu'avec un filtre devant l'objectif. Leur faible respiration et leur faible distorsion les rendent sûres pour les plans-séquences et les effets visuels.",
        atouts = "Homogénéité, peu de respiration, rendu flatteur, poids contenu pour du grand format.",
        limites = "Monture LPL qui les lie aux caméras compatibles, prix élevé.",
        films = listOf(
            "1917" par "Roger Deakins",
            "Invisible Man" par "Stefan Duscio"
        ),
        aRetenir = "Deakins les a associées à l'ALEXA Mini LF pour 1917 : peu de distorsion et peu de respiration, indispensables dans des plans-séquences où le point bouge sans cesse."
    )
)

private fun cooke(): List<Objectif> = listOf(
    Objectif(
        nom = "Speed Panchro",
        fabricant = "Cooke",
        annee = 1930,
        anneeApprox = true,
        categorie = "Focales fixes sphériques, vintage",
        silhouette = Silhouette.ANCIENNE,
        focales = "Fixes courtes à moyennes",
        ouverture = "environ f/2",
        couverture = "35 mm Academy",
        monture = "Réhoussées en PL",
        disponibilite = Disponibilite.PLUS_FABRIQUEE,
        punchline = "Les optiques de l'âge d'or, à l'origine du « Cooke look ».",
        histoire = "Dessinées au début des années 1930 à Leicester, en Angleterre, pour les pellicules panchromatiques — d'où leur nom —, elles ont équipé une grande partie du cinéma classique hollywoodien et britannique. Leur rendu doux et chaleureux sur les visages a donné naissance à l'expression « Cooke look ».",
        ficheTechnique = "Ouverture d'environ f/2, traitements anti-reflets anciens ou absents selon les séries, couverture pensée pour l'image 35 mm Academy. On les trouve aujourd'hui réhoussées en monture PL, avec des bagues de cinéma modernes.",
        commentLUtiliser = "On les choisit pour un film d'époque ou pour adoucir un capteur numérique : contraste bas, halo sur les hautes lumières, carnations flatteuses. Un réhoussage sérieux est indispensable pour une mise au point fiable.",
        atouts = "Douceur, chaleur, beauté des visages, flou progressif.",
        limites = "Couverture limitée, exemplaires hétérogènes, piqué et contraste faibles à pleine ouverture.",
        films = listOf(
            "Citizen Kane" par "Gregg Toland",
            "Les Chaussons rouges" par "Jack Cardiff"
        ),
        aRetenir = "Leur nom vient des pellicules panchromatiques, sensibles à toutes les couleurs, qui remplaçaient alors les émulsions orthochromatiques, aveugles au rouge."
    ),
    Objectif(
        nom = "S4/i",
        fabricant = "Cooke",
        annee = 1998,
        categorie = "Focales fixes sphériques",
        silhouette = Silhouette.FIXE,
        focales = "12 à 300 mm environ",
        ouverture = "T2",
        couverture = "Super 35",
        monture = "PL",
        disponibilite = Disponibilite.PLUS_FABRIQUEE,
        punchline = "La série qui a fait du « Cooke look » un standard moderne.",
        histoire = "Lancées en 1998, elles modernisent la tradition de la maison : un piqué suffisant pour le cinéma contemporain, mais un rendu chaleureux et doux sur les peaux. La série a été arrêtée récemment, après plus de vingt-cinq ans de carrière.",
        ficheTechnique = "Large gamme d'environ 12 à 300 mm, T2 sur toute la série, couverture Super 35. Contacts électroniques transmettant mise au point, diaphragme et focale à la caméra et à la post-production. Existe en version Mini, plus compacte, à T2.8.",
        commentLUtiliser = "Une série de fiction polyvalente : portrait, drame, film d'époque. Les données d'objectif facilitent le travail des effets visuels et le suivi de caméra.",
        atouts = "Carnations chaleureuses, flou doux, homogénéité, robustesse mécanique.",
        limites = "Couverture Super 35 seulement, T2 moins lumineuse que certaines concurrentes, production arrêtée.",
        films = listOf(
            "Munich" par "Janusz Kamiński",
            "Les Heures sombres" par "Bruno Delbonnel",
            "Call Me by Your Name" par "Sayombhu Mukdeeprom"
        ),
        aRetenir = "Le « /i » accolé au nom désigne des contacts électroniques qui transmettent la mise au point et le diaphragme : ces données sont enregistrées avec chaque image."
    ),
    Objectif(
        nom = "Anamorphic/i",
        fabricant = "Cooke",
        annee = 2013,
        categorie = "Anamorphique 2×",
        silhouette = Silhouette.ANAMORPHIQUE,
        focales = "25 à 135 mm (série d'origine)",
        ouverture = "T2.3",
        couverture = "Super 35, puis plein format",
        monture = "PL",
        disponibilite = Disponibilite.ACHAT,
        punchline = "L'anamorphique à la manière Cooke : doux, chaleureux, flares discrets.",
        histoire = "Présentées en 2013, elles appliquent la philosophie de la maison à l'anamorphique 2× : contraste doux, carnations chaudes, flares présents mais maîtrisés. Des versions « SF » (Special Flair), aux traitements plus réactifs, puis des versions plein format ont suivi.",
        ficheTechnique = "Série d'origine de 25, 32, 40, 50, 75, 100 et 135 mm, T2.3, compression 2× pour le Super 35. Données d'objectif intégrées. Variante SF aux flares plus marqués ; versions plein format ensuite.",
        commentLUtiliser = "On tourne en 4:3 ou en open gate pour exploiter la compression 2×, puis on désanamorphose en post-production pour obtenir un format large. Les flares se provoquent en laissant une source entrer légèrement dans le champ.",
        atouts = "Le look scope sans agressivité, avec les carnations flatteuses de la maison.",
        limites = "Flares moins spectaculaires que ceux des anamorphiques vintage ; lourdes et chères.",
        films = listOf(
            "Cuckoo" par "Paul Faltz",
            "Monsieur Aznavour" par "Mehdi Idir, Grand Corps Malade (réal.)"
        ),
        aRetenir = "Une optique anamorphique 2× comprime l'image horizontalement à la prise de vue : en post-production on la redéplie en format très large, et les flous deviennent ovales."
    ),
    Objectif(
        nom = "S7/i",
        fabricant = "Cooke",
        annee = 2017,
        categorie = "Focales fixes plein format",
        silhouette = Silhouette.FIXE,
        focales = "16 à 300 mm environ",
        ouverture = "T2",
        couverture = "Plein format et au-delà",
        monture = "PL",
        disponibilite = Disponibilite.ACHAT,
        punchline = "Le « Cooke look » étendu au grand format.",
        histoire = "Sorties en 2017, elles transposent le rendu chaleureux de la série précédente aux capteurs plein format et VistaVision, au moment où les caméras grand format arrivaient sur les plateaux.",
        ficheTechnique = "Série à T2 couvrant un cercle d'image élargi, données d'objectif intégrées, gamme allant du grand-angle au téléobjectif. Mécanique et rendu dans la continuité de la série Super 35 de la maison.",
        commentLUtiliser = "Le choix naturel d'un chef opérateur habitué au rendu Cooke qui passe au grand format : même douceur, même logique de mise au point.",
        atouts = "Chaleur et douceur en grand format, homogénéité, données d'objectif.",
        limites = "Poids et prix ; moins lumineuses que certaines séries grand format concurrentes.",
        films = listOf("The Last Vermeer" par "Remi Adefarasin"),
        aRetenir = "Elles sont présentées comme « Full Frame Plus » : leur cercle d'image dépasse un peu le plein format photo, pour les capteurs VistaVision qui le débordent."
    ),
    Objectif(
        nom = "Panchro/i Classic",
        fabricant = "Cooke",
        annee = 2017,
        categorie = "Focales fixes, rendu vintage",
        silhouette = Silhouette.FIXE,
        focales = "18 à 152 mm environ",
        ouverture = "environ T2.2",
        couverture = "Super 35, puis plein format",
        monture = "PL",
        disponibilite = Disponibilite.ACHAT,
        punchline = "Les optiques des années 1930 redessinées pour les caméras d'aujourd'hui.",
        histoire = "Présentées en 2017, elles reprennent le dessin optique de la série historique de la maison dans une mécanique moderne, avec données d'objectif. Elles répondent à la demande de rendus anciens sans les aléas des exemplaires d'époque.",
        ficheTechnique = "Formule optique inspirée des séries des années 1930, traitements réglés pour conserver douceur et halo. Mécanique de cinéma actuelle, données d'objectif. Version plein format proposée ensuite.",
        commentLUtiliser = "On les prend pour un film d'époque ou pour une image douce, en sachant que toutes les focales se comportent de la même façon, contrairement aux originaux.",
        atouts = "Caractère vintage homogène et fiable, mise au point précise, données d'objectif.",
        limites = "Moins de « magie » imprévisible que les originaux ; piqué et contraste volontairement bas.",
        films = listOf("The Chosen (série)" par "Akis Konstantakopoulos"),
        aRetenir = "Plutôt que de chercher des exemplaires d'époque tous différents, on obtient le même rendu ancien sur chaque focale, avec la fiabilité d'une optique neuve."
    )
)

private fun angenieux(): List<Objectif> = listOf(
    Objectif(
        nom = "25-250",
        fabricant = "Angénieux",
        annee = 1962,
        categorie = "Zoom 10×, vintage",
        silhouette = Silhouette.ZOOM,
        focales = "Zoom 10×",
        ouverture = "T3.9",
        couverture = "35 mm Academy",
        monture = "Réhoussé en PL",
        disponibilite = Disponibilite.PLUS_FABRIQUEE,
        punchline = "Le « zoom d'Hollywood », qui a fait du zoom avant un style.",
        histoire = "Présenté en 1962 par l'opticien français, ce zoom 10× devient en quelques années un standard mondial, récompensé à Hollywood dès 1964. Il accompagne le cinéma des années 1960 et 1970, où le zoom devient un mouvement expressif et non plus un simple outil.",
        ficheTechnique = "Zoom 10× ouvrant à f/3.2, soit environ T3.9, couverture 35 mm. Plusieurs versions se succèdent, dont une version HR à haute résolution. On le trouve aujourd'hui réhoussé en monture PL.",
        commentLUtiliser = "Il demande beaucoup de lumière à T3.9. On l'emploie pour des zooms lents qui resserrent sur un visage ou révèlent un décor, dans l'esprit des années 1970.",
        atouts = "Une amplitude focale énorme en un seul objectif, le rendu des années 1970, des zooms fluides.",
        limites = "Peu lumineux, piqué modeste sur les bords, poids ; un bon réhoussage est indispensable.",
        films = listOf(
            "Un homme et une femme" par "Claude Lelouch",
            "Le Parrain" par "Gordon Willis",
            "Apocalypse Now" par "Vittorio Storaro"
        ),
        aRetenir = "Surnommé le « Hollywood zoom », il a valu à son fabricant un Oscar scientifique et technique en 1964, deux ans seulement après sa sortie."
    ),
    Objectif(
        nom = "Optimo 24-290",
        fabricant = "Angénieux",
        annee = 2001,
        categorie = "Zoom 12×, studio",
        silhouette = Silhouette.ZOOM,
        focales = "24 à 290 mm",
        ouverture = "T2.8",
        couverture = "Super 35",
        monture = "PL",
        disponibilite = Disponibilite.ACHAT,
        punchline = "Le zoom de studio de référence, présent sur presque tous les grands tournages.",
        histoire = "Sorti en 2001 des ateliers de Saint-Héand, près de Saint-Étienne, il s'impose immédiatement : un zoom 12× assez lumineux et net pour remplacer une série d'optiques fixes. Il est depuis la pièce maîtresse du camion caméra des longs-métrages, publicités et séries.",
        ficheTechnique = "Zoom 12× de 24 à 290 mm, T2.8 constant, couverture Super 35. Ni respiration ni variation d'ouverture sur la course du zoom. Un peu plus de 11 kg : il se porte sur un support d'objectif.",
        commentLUtiliser = "Sur pied ou grue avec une tête lourde, il permet de recadrer sans déplacer la caméra et de tourner à longue focale en gardant le rendu d'une série fixe. Sa masse impose une machinerie adaptée.",
        atouts = "La qualité d'une focale fixe sur une amplitude énorme, un zoom sans respiration.",
        limites = "Poids et encombrement considérables, inadapté à l'épaule comme aux stabilisateurs légers.",
        films = listOf("Skyfall" par "Roger Deakins"),
        aRetenir = "Il est fabriqué en France, dans la Loire : son fabricant est l'une des rares références mondiales du zoom de cinéma."
    ),
    Objectif(
        nom = "EZ-1 et EZ-2",
        fabricant = "Angénieux",
        annee = 2016,
        categorie = "Zooms légers, Super 35 ou plein format",
        silhouette = Silhouette.ZOOM,
        focales = "30-90 et 15-40 mm (S35), 45-135 et 22-60 mm (plein format)",
        ouverture = "T2 (S35), T3 (plein format)",
        couverture = "Super 35 ou plein format",
        monture = "Interchangeable : PL, EF, E",
        disponibilite = Disponibilite.ACHAT,
        punchline = "Deux zooms légers qui passent du Super 35 au plein format en changeant leur arrière.",
        histoire = "Présentés en 2016, ils visent les tournages légers qui veulent la qualité de la maison sans le poids des grands zooms de studio. Leur particularité : un groupe optique arrière interchangeable qui fait passer chaque zoom de la couverture Super 35 à la couverture plein format.",
        ficheTechnique = "Le premier couvre 30-90 mm à T2 en Super 35, ou 45-135 mm à T3 en plein format ; le second 15-40 mm à T2 en Super 35, ou 22-60 mm à T3 en plein format. Montures interchangeables. Légers pour des zooms de cinéma.",
        commentLUtiliser = "On passe d'une caméra Super 35 à une caméra plein format en changeant le bloc arrière plutôt que tout le parc. Idéaux sur stabilisateur, en documentaire ou comme zooms d'appoint.",
        atouts = "Polyvalence de format, légèreté, rendu de la maison, prix plus accessible.",
        limites = "Moins lumineux en plein format, amplitude plus courte que les grands zooms de studio.",
        films = listOf("Les Gardiens de la Galaxie Vol. 3" par "Henry Braham"),
        aRetenir = "Le même zoom change de format : on remplace le groupe de lentilles arrière, et la focale comme l'ouverture changent avec lui."
    )
)

private fun leitz(): List<Objectif> = listOf(
    Objectif(
        nom = "Summilux-C et Summicron-C",
        fabricant = "Leitz",
        annee = 2009,
        categorie = "Focales fixes sphériques",
        silhouette = Silhouette.FIXE,
        focales = "16 à 135 mm selon la série",
        ouverture = "T1.4 (Summilux-C), T2 (Summicron-C)",
        couverture = "Super 35",
        monture = "PL",
        disponibilite = Disponibilite.ACHAT,
        punchline = "Les premières optiques de cinéma de Leica : compactes, lumineuses, d'un piqué doux.",
        histoire = "Présentées fin 2009, les plus lumineuses sont les premières optiques de cinéma de l'histoire de Leica, fabriquées par sa branche cinéma aujourd'hui appelée Leitz. Une seconde série, un peu moins lumineuse et plus compacte, a suivi.",
        ficheTechnique = "T1.4 pour la première série, T2 pour la seconde, couverture Super 35. Corps très compacts, de dimensions presque identiques d'une focale à l'autre, course de mise au point longue et précise.",
        commentLUtiliser = "Leur taille identique évite de rééquilibrer le stabilisateur et la matte box à chaque changement de focale : un vrai gain de temps en Steadicam et sur les tournages rapides.",
        atouts = "Luminosité, compacité, rendu doux mais net, flou naturel.",
        limites = "Couverture Super 35 ; tarif haut de gamme.",
        films = listOf("The Killer" par "Erik Messerschmidt"),
        aRetenir = "C'est la première incursion de Leica dans l'optique de cinéma, après près d'un siècle de photographie."
    ),
    Objectif(
        nom = "Thalia",
        fabricant = "Leitz",
        annee = 2017,
        categorie = "Focales fixes grand format",
        silhouette = Silhouette.FIXE,
        focales = "24 à 180 mm environ",
        ouverture = "T2.2 à T3.6 selon la focale",
        couverture = "Jusqu'au 65 mm",
        monture = "PL",
        disponibilite = Disponibilite.ACHAT,
        punchline = "Des optiques issues du moyen format photo, pour les très grands capteurs.",
        histoire = "Lancées en 2017, elles dérivent des objectifs du système photo moyen format de Leica. Leur cercle d'image couvre les capteurs 65 mm : elles accompagnent les plus grandes caméras avec un rendu doux, sans agressivité.",
        ficheTechnique = "Cercle d'image d'environ 60 mm, adapté aux capteurs 65 mm. Ouvertures de T2.2 à T3.6 selon les focales. Corps légers pour leur couverture. Piqué fin sans dureté, transitions de flou douces.",
        commentLUtiliser = "On les choisit pour les tournages grand format qui veulent une image picturale plutôt que clinique : portraits, films d'époque.",
        atouts = "Couverture extrême, légèreté, rendu doux et pictural.",
        limites = "Ouvertures modestes pour du grand format, exigeantes en lumière.",
        films = listOf(
            "Portrait de la jeune fille en feu" par "Claire Mathon",
            "Frankenstein (2025)" par "Dan Laustsen"
        ),
        aRetenir = "Claire Mathon les a choisies pour Portrait de la jeune fille en feu : un rendu de tableau, pour l'histoire d'une peintre et de son modèle."
    )
)

private fun panavisionOptiques(): List<Objectif> = listOf(
    Objectif(
        nom = "C-Series",
        fabricant = "Panavision",
        annee = 1968,
        categorie = "Anamorphique 2×, vintage",
        silhouette = Silhouette.ANAMORPHIQUE,
        focales = "Fixes de 35 à 180 mm environ",
        ouverture = "environ T2.3 à T3",
        couverture = "35 mm anamorphique",
        monture = "Panavision",
        disponibilite = Disponibilite.LOCATION_EXCLUSIVE,
        punchline = "Le scope du Nouvel Hollywood : flares bleus, flous ovales.",
        histoire = "Introduite en 1968, cette série d'anamorphiques compacts et légers a équipé une grande partie du cinéma des années 1970 et 1980. Comme tout le parc de la maison, elle ne se vend pas : elle se loue, et des exemplaires d'origine tournent encore.",
        ficheTechnique = "Anamorphiques 2×, compacts pour l'époque. Profondeur de champ progressive, flares horizontaux prononcés, flou ovale caractéristique, légère distorsion. Monture Panavision.",
        commentLUtiliser = "On les réserve aux films qui veulent la texture du scope classique. Leur distance minimale de mise au point est longue : pour les gros plans très serrés, il faut d'autres optiques ou des bonnettes.",
        atouts = "Flares et flous mythiques, légèreté, rendu organique.",
        limites = "Mise au point minimale éloignée, exemplaires tous légèrement différents, location exclusive.",
        films = listOf(
            "Les Dents de la mer" par "Bill Butler",
            "La Guerre des étoiles" par "Gilbert Taylor",
            "Star Wars : Le Réveil de la Force" par "Dan Mindel"
        ),
        aRetenir = "La même série a servi à La Guerre des étoiles en 1977 et au Réveil de la Force en 2015 : un moyen de retrouver la texture de la trilogie d'origine."
    ),
    Objectif(
        nom = "Primo",
        fabricant = "Panavision",
        annee = 1987,
        anneeApprox = true,
        categorie = "Focales fixes et zooms sphériques",
        silhouette = Silhouette.FIXE,
        focales = "Fixes de 10 à 150 mm, zooms assortis",
        ouverture = "T1.9 (fixes)",
        couverture = "35 mm",
        monture = "Panavision",
        disponibilite = Disponibilite.LOCATION_EXCLUSIVE,
        punchline = "La première famille de fixes et de zooms parfaitement assortis.",
        histoire = "Apparues à la fin des années 1980 — L'Empire du soleil de Spielberg est le premier film à les utiliser —, elles forment la première gamme où fixes et zooms partagent le même rendu. Récompensées par l'Académie, elles ont défini l'image des années 1990.",
        ficheTechnique = "Fixes à T1.9 et zooms assortis, contraste élevé, peu de reflets parasites, distorsion faible. Couverture 35 mm, monture Panavision. Déclinées depuis en séries grand format.",
        commentLUtiliser = "On mélange fixes et zooms dans une même séquence sans que l'étalonnage ne voie la différence. Série de travail polyvalente pour toute la fiction.",
        atouts = "Homogénéité entre fixes et zooms, contraste, fiabilité.",
        limites = "Location exclusive, rendu très net et contrasté, moins à la mode face aux optiques à caractère.",
        films = listOf(
            "L'Empire du soleil" par "Allen Daviau",
            "Casino" par "Robert Richardson",
            "Titanic" par "Russell Carpenter"
        ),
        aRetenir = "Pour la première fois, fixes et zooms d'une même marque rendaient exactement la même image : on pouvait couper d'un plan au zoom à un plan à la focale fixe sans rien voir."
    ),
    Objectif(
        nom = "Primo 70 et Sphero 65",
        fabricant = "Panavision",
        annee = 2014,
        anneeApprox = true,
        categorie = "Focales fixes grand format (65 mm)",
        silhouette = Silhouette.FIXE,
        focales = "Du grand-angle au téléobjectif",
        ouverture = "Variable selon la focale",
        couverture = "65 mm",
        monture = "Panavision grand format",
        disponibilite = Disponibilite.LOCATION_EXCLUSIVE,
        punchline = "Deux visages du 65 mm chez Panavision : net et moderne, ou doux et classique.",
        histoire = "Avec le retour du grand format numérique, Panavision propose au milieu des années 2010 deux séries couvrant les capteurs 65 mm : la première moderne, nette et contrastée, avec moteurs et données d'objectif intégrés ; la seconde au rendu plus doux et plus classique.",
        ficheTechnique = "Couverture 65 mm. Première série : optiques modernes à contraste élevé, moteurs de mise au point internes et données d'objectif. Seconde série : rendu plus doux, dans l'esprit des optiques grand format d'autrefois. Location uniquement.",
        commentLUtiliser = "On choisit selon l'intention : la série moderne pour une image nette et spectaculaire, la série classique pour adoucir un très grand capteur. Les deux s'emploient sur des caméras grand format comme la DXL2 ou l'ALEXA 65.",
        atouts = "Couverture 65 mm, deux rendus au choix, intégration électronique de la série moderne.",
        limites = "Location exclusive et coûteuse, poids, profondeur de champ très courte en grand format.",
        films = listOf(
            "Mission: Impossible – Fallout" par "Rob Hardy",
            "The Greatest Showman" par "Seamus McGarvey",
            "Live by Night" par "Robert Richardson"
        ),
        aRetenir = "The Greatest Showman a mélangé les deux séries : le net moderne et le doux classique dans un même film en grand format."
    ),
    Objectif(
        nom = "T-Series",
        fabricant = "Panavision",
        annee = 2016,
        anneeApprox = true,
        categorie = "Anamorphique 2×, moderne",
        silhouette = Silhouette.ANAMORPHIQUE,
        focales = "Fixes et zooms",
        ouverture = "Variable selon la focale",
        couverture = "35 mm anamorphique",
        monture = "Panavision",
        disponibilite = Disponibilite.LOCATION_EXCLUSIVE,
        punchline = "L'anamorphique Panavision moderne : compact et capable de filmer de très près.",
        histoire = "Série anamorphique récente de la maison, conçue pour les caméras numériques comme pour la pellicule. Elle reprend l'esthétique des séries anciennes mais corrige leur principal défaut : une distance minimale de mise au point trop grande pour les gros plans.",
        ficheTechnique = "Anamorphiques 2×, compacts et légers, mise au point rapprochée bien meilleure que celle des séries historiques. Flares et flous ovales dans la tradition de la maison, contraste moderne. Monture Panavision.",
        commentLUtiliser = "On les choisit quand la mise en scène va chercher les visages de très près en scope. Ils se mélangent sans heurt aux séries plus anciennes dans un même film.",
        atouts = "Mise au point rapprochée, compacité, look anamorphique fiable.",
        limites = "Moins de « défauts » charmants que les séries vintage, location exclusive.",
        films = listOf(
            "Killers of the Flower Moon" par "Rodrigo Prieto",
            "Once Upon a Time… in Hollywood" par "Robert Richardson"
        ),
        aRetenir = "Sur Once Upon a Time… in Hollywood, Richardson voulait ses anamorphiques anciens habituels, mais la mise en scène exigeait de filmer à moins de soixante centimètres : cette série a été adaptée pour ça."
    )
)

private fun anamorphiques(): List<Objectif> = listOf(
    Objectif(
        nom = "Cine Prominar anamorphiques",
        fabricant = "Kowa",
        annee = 1970,
        anneeApprox = true,
        categorie = "Anamorphique 2×, vintage japonais",
        silhouette = Silhouette.ANAMORPHIQUE,
        focales = "Fixes courtes à moyennes",
        ouverture = "Variable selon la focale",
        couverture = "35 mm anamorphique",
        monture = "Réhoussées en PL",
        disponibilite = Disponibilite.PLUS_FABRIQUEE,
        punchline = "Des anamorphiques japonais compacts, revenus en force dans les années 2010.",
        histoire = "Fabriqués au Japon dans les années 1970 et 1980, ces anamorphiques compacts ont longtemps été oubliés avant de revenir, réhoussés, sur des films qui cherchaient une texture ancienne en numérique.",
        ficheTechnique = "Anamorphiques 2× à élément anamorphique frontal, très compacts. Flares bleutés, douceur sur les bords, flou ovale. Exemplaires d'époque réhoussés en monture PL.",
        commentLUtiliser = "On les associe à une caméra numérique pour casser sa netteté. Chaque exemplaire a sa personnalité : on les teste avant le tournage et l'on apprend leurs réactions aux sources dans le champ.",
        atouts = "Compacité, caractère vintage, flares et douceur recherchés.",
        limites = "Exemplaires rares et inégaux, mécanique d'origine, dépendance au réhousseur.",
        films = listOf(
            "First Man : le premier homme sur la Lune" par "Linus Sandgren",
            "A Star Is Born" par "Matthew Libatique"
        ),
        aRetenir = "Longtemps délaissés, ils ont retrouvé les plateaux avec la génération numérique, qui cherchait à réintroduire des défauts dans des images devenues trop parfaites."
    ),
    Objectif(
        nom = "Square Front et Round Front",
        fabricant = "LOMO",
        annee = 1970,
        anneeApprox = true,
        categorie = "Anamorphique 2×, soviétique",
        silhouette = Silhouette.ANAMORPHIQUE,
        focales = "Fixes de 35 à 100 mm environ",
        ouverture = "Variable selon la focale",
        couverture = "35 mm anamorphique",
        monture = "Réhoussées en PL",
        disponibilite = Disponibilite.PLUS_FABRIQUEE,
        punchline = "Les anamorphiques du cinéma soviétique, recherchés pour leur caractère.",
        histoire = "Fabriqués à Leningrad, les modèles à façade carrée des années 1970 puis ceux à façade ronde, plus fiables, ont été au cinéma soviétique ce que les Panavision étaient à Hollywood. Recherchés en Occident, ils ont même lancé l'activité du loueur allemand Vantage, qui a commencé par les réhousser.",
        ficheTechnique = "Anamorphiques 2×. Les versions à façade ronde sont plus nettes, respirent moins et mettent au point plus près que celles à façade carrée. Centre net, bords plus doux, flares et flous ovales marqués.",
        commentLUtiliser = "On les choisit pour un scope texturé, un peu sale. Les modèles à façade carrée peuvent déformer les visages en mise au point rapprochée — l'effet dit des « oreillons » : on vérifie chaque exemplaire.",
        atouts = "Look vintage prononcé, flares et flous mémorables, coût inférieur aux séries hollywoodiennes.",
        limites = "Hétérogénéité, mécanique ancienne, défauts optiques pas toujours désirables.",
        films = listOf("I Think We're Alone Now" par "Reed Morano"),
        aRetenir = "LOMO signifie « Association d'optique et de mécanique de Leningrad » : le grand opticien d'État soviétique."
    ),
    Objectif(
        nom = "Hawk V-Lite",
        fabricant = "Vantage",
        annee = 2008,
        anneeApprox = true,
        categorie = "Anamorphique 2×, moderne",
        silhouette = Silhouette.ANAMORPHIQUE,
        focales = "Fixes courtes à longues",
        ouverture = "Variable selon la focale",
        couverture = "35 mm anamorphique",
        monture = "PL",
        disponibilite = Disponibilite.LOCATION,
        punchline = "Les anamorphiques allemands allégés, taillés pour la Steadicam et les stabilisateurs.",
        histoire = "Vantage, fondée en Allemagne en 1993 pour ramener l'anamorphique dans la production courante, lance ces versions allégées à la fin des années 2000 : l'esthétique de ses séries lourdes pour près de moitié moins de poids. Une variante « Vintage '74 » reproduit des traitements anciens.",
        ficheTechnique = "Anamorphiques 2×, corps légers et compacts pour leur catégorie. Rendu net et contrasté dans la version standard, plus doux et plus riche en flares dans la version Vintage '74.",
        commentLUtiliser = "On les monte en Steadicam, sur stabilisateur ou à l'épaule, là où les anamorphiques lourds deviennent pénibles.",
        atouts = "Légèreté, fiabilité mécanique moderne, choix entre rendu net et rendu vintage.",
        limites = "Rendu standard parfois jugé trop propre ; disponibilité liée aux loueurs.",
        films = listOf("Moonlight" par "James Laxton"),
        aRetenir = "Moonlight a été tourné avec une seule caméra et ces optiques : un scope intime, loin de l'usage spectaculaire habituel de l'anamorphique."
    )
)

private fun vintageEtAlternatives(): List<Objectif> = listOf(
    Objectif(
        nom = "Baltar",
        fabricant = "Bausch & Lomb",
        annee = 1935,
        anneeApprox = true,
        categorie = "Focales fixes sphériques, vintage",
        silhouette = Silhouette.ANCIENNE,
        focales = "Fixes classiques",
        ouverture = "environ f/2.3",
        couverture = "35 mm Academy",
        monture = "Réhoussées en PL",
        disponibilite = Disponibilite.PLUS_FABRIQUEE,
        punchline = "Les optiques de l'âge d'or hollywoodien, douces et imparfaites.",
        histoire = "Conçues dans les années 1930 par l'opticien américain Bausch & Lomb, elles ont équipé les caméras de studio hollywoodiennes pendant des décennies. Leur formule simple, antérieure aux traitements anti-reflets modernes, leur donne une douceur et un halo aujourd'hui recherchés.",
        ficheTechnique = "Formule optique simple, peu d'éléments, traitements anciens ou absents. Contraste bas, halo sur les hautes lumières, vignetage et distorsions sur les bords. Exemplaires réhoussés pour les caméras actuelles.",
        commentLUtiliser = "On les réserve aux projets qui veulent une image d'époque : elles adoucissent, baissent le contraste et déforment légèrement les bords. On teste chaque focale, car les exemplaires varient.",
        atouts = "Beauté des portraits, douceur, authenticité d'époque.",
        limites = "Piqué faible, contraste bas, rareté, fiabilité variable.",
        films = listOf("The Lighthouse" par "Jarin Blaschke"),
        aRetenir = "Pour The Lighthouse, Jarin Blaschke les a trouvées chez Panavision et les a décrites comme les plus belles optiques de portrait qu'il ait jamais vues."
    ),
    Objectif(
        nom = "K35",
        fabricant = "Canon",
        annee = 1975,
        anneeApprox = true,
        categorie = "Focales fixes sphériques, vintage",
        silhouette = Silhouette.ANCIENNE,
        focales = "18, 24, 35, 55 et 85 mm",
        ouverture = "T1.3 à T1.5",
        couverture = "Super 35",
        monture = "Réhoussées en PL",
        disponibilite = Disponibilite.PLUS_FABRIQUEE,
        punchline = "Les fixes lumineuses de Canon des années 1970, aux reflets dorés.",
        histoire = "Canon les lance dans les années 1970 comme réponse aux séries ultra-lumineuses de Zeiss. Leur formule à lentille asphérique leur vaut un Oscar scientifique et technique en 1977. Réhoussées, elles sont aujourd'hui parmi les optiques vintage les plus demandées.",
        ficheTechnique = "Série de 18, 24, 35, 55 et 85 mm, T1.3 à T1.5, lentille asphérique. Rendu chaud, contraste doux, flares ambrés. Réhoussages modernes en monture PL.",
        commentLUtiliser = "On les associe à un capteur numérique pour le réchauffer et l'adoucir. Très lumineuses, elles servent aussi en lumière faible, avec une mise au point exigeante à pleine ouverture.",
        atouts = "Chaleur, luminosité, flares dorés, caractère des années 1970.",
        limites = "Série courte, exemplaires anciens, piqué moindre à pleine ouverture.",
        films = listOf(
            "Barry Lyndon" par "John Alcott",
            "Aliens, le retour" par "Adrian Biddle"
        ),
        aRetenir = "Barry Lyndon est célèbre pour son objectif Zeiss de la NASA ouvrant à f/0.7, utilisé à la lueur des bougies ; mais ce sont ces optiques Canon qui ont tourné une grande partie du film, notamment les extérieurs."
    ),
    Objectif(
        nom = "AI-S réhoussés",
        fabricant = "Nikon",
        annee = 1981,
        categorie = "Optiques photo reconverties",
        silhouette = Silhouette.ANCIENNE,
        focales = "15 à 135 mm selon les réhoussages",
        ouverture = "Variable selon la focale",
        couverture = "Plein format",
        monture = "PL (réhoussage)",
        disponibilite = Disponibilite.PLUS_FABRIQUEE,
        punchline = "Des objectifs photo des années 1980, transformés en optiques de cinéma.",
        histoire = "Les objectifs photo de cette génération, apparue en 1981, sont réputés pour leur rendu organique. Des ateliers spécialisés les démontent et les remontent dans des fûts de cinéma, avec bagues crantées et monture PL, pour offrir à bas prix un caractère que les séries neuves n'ont plus.",
        ficheTechnique = "Optiques photo couvrant le plein format, réhoussées avec bagues de mise au point et de diaphragme crantées et course allongée. Rendu doux, carnations naturelles, flares maîtrisés.",
        commentLUtiliser = "On vérifie l'homogénéité de couleur entre les focales, puisqu'il ne s'agissait pas d'une série de cinéma conçue d'un bloc. Leur prix permet une série à caractère pour un petit budget.",
        atouts = "Caractère, plein format, coût modéré, légèreté.",
        limites = "Homogénéité imparfaite, respiration et mise au point moins précises qu'une véritable série de cinéma.",
        films = listOf("True Things" par "Ashley Connor"),
        aRetenir = "Réhousser, c'est garder les lentilles et changer tout le reste : un objectif photo devient une optique de cinéma sans qu'on touche au verre."
    ),
    Objectif(
        nom = "Cine FF High Speed",
        fabricant = "Sigma",
        annee = 2016,
        categorie = "Focales fixes plein format, accessibles",
        silhouette = Silhouette.FIXE,
        focales = "14 à 135 mm",
        ouverture = "T1.5 (T2 aux extrêmes)",
        couverture = "Plein format",
        monture = "PL, EF ou E",
        disponibilite = Disponibilite.ACHAT,
        punchline = "Des fixes plein format très lumineuses, à prix accessible.",
        histoire = "Présentées en 2016, elles dérivent des objectifs photo haut de gamme de la marque, redessinés en mécanique de cinéma. Elles ont rendu le plein format lumineux accessible aux petites productions, avant de monter en grade jusqu'aux gros tournages.",
        ficheTechnique = "Série de 14 à 135 mm, T1.5 pour l'essentiel, couverture plein format, définition adaptée au 8K. Construction étanche à la poussière et aux projections. Montures PL, EF ou E, version avec données d'objectif.",
        commentLUtiliser = "Série principale d'une production plein format modeste, ou série d'appoint lumineuse. Leur étanchéité les rend fiables en extérieur.",
        atouts = "Luminosité, piqué, prix, robustesse.",
        limites = "Rendu net et moderne, peu de caractère ; plus lourdes que certaines séries haut de gamme.",
        films = listOf("Top Gun: Maverick (focales courtes)" par "Claudio Miranda"),
        aRetenir = "Sur Top Gun: Maverick, ce sont elles qui couvraient les focales de 14 à 40 mm de l'équipe principale, des optiques haut de gamme prenant le relais au-delà."
    )
)
